module.exports = {
  compact: true,
  controlFlowFlattening: true,
  controlFlowFlatteningThreshold: 0.7,
  deadCodeInjection: true,
  deadCodeInjectionThreshold: 0.3,
  identifierNamesGenerator: 'hexadecimal',
  renameGlobals: false,
  rotateStringArray: true,
  stringArray: true,
  stringArrayEncoding: ['rc4'],
  stringArrayThreshold: 0.75,
  unicodeEscapeSequence: false,
  selfDefending: true,
  transformObjectKeys: true,
  splitStrings: true,
  splitStringsChunkLength: 5,
  reservedNames: [
    'doGet',
    'api_login', 'api_logout', 'api_validateSession',
    'api_changePassword', 'api_adminResetPassword',
    'api_lockUser', 'api_unlockUser',
    'api_getUsers', 'api_addUser', 'api_updateUser',
    'api_getApps', 'api_addApp', 'api_updateApp', 'api_deleteApp',
    'api_getSsoParams',
    'api_getMailConfig', 'api_saveMailConfig',
  ],
}
